#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [5.6]

cache:
  apt: true
  directories:
    - /var/cache/apt/archives/apt-fast/

before_install:
  # shutdown stuff on Travis, which may have a memory impact
  - sudo service --status-all
  - sudo free -m -t
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/couchdb stop
  - sudo /etc/init.d/redis-server stop
  - sudo free -m -t
  # install apt-fast to speedup later dependency installation
  - sudo add-apt-repository -y ppa:apt-fast/stable
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa #< wine 1.17.8
  - sudo add-apt-repository -y ppa:t-tujikawa/ppa #< aria2 (we need newer version, because stable version has SSL issues.)
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-fast
  # use apt-fast for installation of dependencies
  - sudo apt-fast -y update
  - sudo apt-fast -m -y install aria2 p7zip-full upx ca-certificates wine1.7

before_script:
  # start framebuffer (wine wants this)
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 640x480x16 -noreset"
  # adjust PHP env
  - phpenv config-add .travis.php.ini   # < increase memory
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then phpenv config-rm xdebug.ini; fi # < disable xdebug on PHP 5.6

script:
  #- sudo /opt/wine-staging/bin/wine --version
  #- wine --version #< ubuntu-wine/ppa
  #- wineconsole --version
  - aria2c --version
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar main-part1
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar download-components
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar main-part2
  # show content of folders
  - sudo ls -alh /home/travis/build/WPN-XM/WPN-XM/*
  - sudo ls -alh /home/travis/build/WPN-XM/WPN-XM/downloads/*

after_failure:
  - sudo free -m -t
  - sudo dmesg # < WTF is wrong with Travis?

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# deploy the installer executables to github releases
deploy:
  provider: releases
  api_key:
    secure: EXN1Q+iXC9acOgUujeCxCQywzDCLQUWQbAa8GMxnqF1nBAvSDeXnTIBQnfDsuQZkWtSMz34zyC4ZN/eta9Lytq4yKMP4XvKVBP5bXQNanDzck+CuUFbnYKE8bVbON6mksN09H5/qt0QHWxjE/vlxCXdoD7Kaek3coWET9s82yXg=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/_build/*.exe
  skip_cleanup: true
  on:
    tags: true #  the application is deployed, when a tag is applied to the commit